name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install xvfbwrapper
    - name: Run script with xvfb
      run: |
        export DISPLAY=:99.0
        Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
        python Weather.py
